steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/crack-glider-470520-r7/aletheia-repo/aletheia-os:latest', '.']

images:
- 'us-central1-docker.pkg.dev/crack-glider-470520-r7/aletheia-repo/aletheia-os:latest'

logsBucket: 'gs://crack-glider-470520-r7-build-logs'
